platform :ios, '10.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false

source 'git@github.com:applicaster/CocoaPods.git'
source 'git@github.com:applicaster/CocoaPods-Private.git'
source 'https://cdn.cocoapods.org/'

target 'JWPlayerPlugin' do
  platform :ios, '10.0'
  pod 'ZappCore'
  pod 'ApplicasterSDK'
  pod 'JWPlayer-SDK'
  pod 'JWPlayerPlugin', :path => 'JWPlayerPlugin.podspec'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.1'
        end
    end
end

